name: End-to-end tests
on: [push]

jobs:
  job1:
    name: cypress-test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        run: | 
          cd pick-up-game-finder
          ls
        uses: cypress-io/github-action@v1
