name: End-to-end tests
on: [push]

jobs:
  job1:
    name: Cypress
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Frontend-install
        run: npm ci

      - name: Get-backend
        uses: actions/checkout@v2
        with: 
          repository: OlliJ5/PickupGameFinder-back
          path: backend

      - name: Backend-install
        working-directory: ./backend
        run: npm ci

      - name: Cypress run
        env:
          BACK_PORT: 6969
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}
        uses: cypress-io/github-action@v1
        with:
          start: npm run actions-start
          wait-on: 'http://localhost:3000'

  job2:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: ESLint
        run: npm run eslint
