name: End-to-end tests
on: [push]

jobs:
  job1:
    name: cypress-test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get-backend
        uses: actions/checkout@v2
        with: 
          repository: OlliJ5/PickupGameFinder-back
          path: backend

      - name: debug
        run: |
          ls

      - name: Backend-install
        # env:
        #   PORT: 6969
        #   TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
        #   SECRET: ${{ secrets.SECRET }}
        working-directory: ./backend
        run: |
          ls
          npm ci
          # npm run start:test
          ls

      - name: Cypress run
        env:
          PORT: 6969
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}
        uses: cypress-io/github-action@v1
        with:
          start: npm run actions-start
          wait-on: 'http://localhost:3000'
