name: End-to-end tests
on: [push]

jobs:
  job1:
    name: cypress-test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get-backend
        uses: actions/checkout@v2
        with: 
          repository: OlliJ5/PickupGameFinder-back
          path: backend

      - name: Start-backend
        working-directory: ./backend
        run: |
          ls
          npm ci
          npm run start:test

      - name: Cypress run
        uses: cypress-io/github-action@v1
